apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  annotations:
  # This is what defines this resource as a hook. Without this line, the
  # job is considered part of the release.
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
      - name: test
        image: busybox
        args:
        - "sleep"
        - "30"
      restartPolicy: Never